publish_mode: editorial_workflow
backend:
  name: github
  repo: bloom-works/child-welfare-playbook-v2
  branch: main
  site_domain: child-welfare-playbook-v2.netlify.app
site_url: https://child-welfare-playbook-v2.netlify.app
display_url: https://childwelfareplaybook.com
media_folder: 'images'
collections:
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - label: "Homepage"
        name: "home"
        file: "_data/home.yml"
        fields:
          - { label: "Meta description", name: "description", widget: "string", required: false }
          - { label: "Banner subheader", name: "bannerSubheader", widget: "markdown", minimal: true, required: false }
          - { label: "Topics section header", name: "topicHeader", widget: "string", required: false }
          - { label: "Topics section subheader", name: "topicSubheader", widget: "markdown", minimal: true, required: false }
          - { label: "Stories section header", name: "storyHeader", widget: "string", required: false }
          - { label: "Stories section subheader", name: "storySubheader", widget: "markdown", minimal: true, required: false }
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Meta description", name: "metaDescription", widget: "string", required: false }
          - { label: "Banner subheader", name: "pageDescription", widget: "markdown", minimal: true, required: false }
          - { label: "Content", name: "content", widget: "markdown", required: false }
          - { label: "URL redirect(s)", minimize_collapsed: true, name: "redirectFrom", widget: "list", label_singular: "redirect", allow_add: true, field: {label: "URL", name: "url", widget: "string"}, required: false }
      - label: "Search"
        name: "search"
        file: "_data/search.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Meta description", name: "metaDescription", widget: "string", required: false }
          - { label: "Banner subheader", name: "pageDescription", widget: "markdown", minimal: true, required: false }
          - { label: "URL redirect(s)", minimize_collapsed: true, name: "redirectFrom", widget: "list", label_singular: "redirect", allow_add: true, field: {label: "URL", name: "url", widget: "string"}, required: false }
      - label: "Meetings and dashboard page meta descriptions"
        name: "meetingsDashboards"
        file: "_data/meetingsDashboards.yml"
        fields:
          - { label: "Meetings page meta description", name: "meetingsMetaDescription", widget: "string", required: false }
          - { label: "Dashboards page meta description", name: "dashboardsMetaDescription", widget: "string", required: false }
      - label: "Footer"
        name: "footer"
        file: "_data/footer.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "markdown", required: false }
          - { label: "Button text", name: "buttonText", widget: "markdown", minimal: true, required: false }
          - { label: "Button URL", name: "buttonURL", widget: "string", required: false }
          - { label: "Copyright credit", name: "credit", widget: "string", required: false }
      - label: "Adam Walsh Dashboard page"
        name: "adamWalsh"
        file: "_data/adamWalsh.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro copy", name: "intro", widget: "markdown", required: false }

  - name: "topics"
    label: "Topics"
    folder: "topics"
    create: true
    label_singular: "topic"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/topic.njk" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Name of topic", name: "title", widget: "string" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "URL", name: "permalink", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "string", required: false }
      - { label: "Icon", name: "icon", widget: "string" }
      - { label: "Introduction", name: "body", widget: "markdown" }
      - { label: "Summary", name: "summary", hint: "For search engines and the topic card that appears in the homepage."}
      - { label: "Related topics", required: false, name: "related", widget: "relation", collection: "topics", value_field: "id", search_fields: ["title", "id"], multiple: true}
      - { label: "URL redirect(s)", minimize_collapsed: true, name: "redirectFrom", widget: "list", label_singular: "redirect", allow_add: true, field: {label: "URL", name: "url", widget: "string"}, required: false }
  - name: "strategies"
    label: "Strategies"
    folder: "strategies"
    create: true
    label_singular: "strategy"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/strategy.njk" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false, hint: "Format your permalink like: '/strategies/strategy-name/'. Make sure to include the backslash at the end, and to omit the childwelfareplaybook.com domain." }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["background-checks", "emergency-placements", "supporting-older-youth", "caregiver-licensing", "kin-engagement", "prevention", "recruitment", "retention", "supportive-relationships", "strategy", "resource", "story"], default: ["strategy"], hint: "Add your topics here"}
      - { label: "Order", name: "order", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Related resources", required: false, name: "resources", widget: "relation", collection: "resources", value_field: "title", search_fields: ["title", "url"], multiple: true}
      - { label: "Related stories", required: false, name: "stories", widget: "relation", collection: "stories", value_field: "title", search_fields: ["title", "url"], multiple: true}
      - { label: "URL redirect(s)", minimize_collapsed: true, name: "redirectFrom", widget: "list", label_singular: "redirect", allow_add: true, field: {label: "URL", name: "url", widget: "string"}, required: false }
  - name: "stories"
    label: "Stories"
    folder: "stories"
    label_singular: "story"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/story.njk" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false, hint: "Format your permalink like: '/stories/story-name/'. Make sure to include the backslash at the end, and to omit the childwelfareplaybook.com domain." }
      - { label: "One-sentence summary", name: "description", widget: "string", hint: "For post thumbnails and social media previews." }
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}", date_format: "YYYY-MM-DD"}
      - { label: "Story type", name: "type", widget: "select", options: ["Blog post", "Case study", "Research report"], default: ["Blog post"]}
      - { label: "Header image", name: "image", widget: "image", allow_multiple: false, media_folder: "/images/stories", public_folder: ".images/stories/", required: false}
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["background-checks", "emergency-placements", "supporting-older-youth", "caregiver-licensing", "kin-engagement", "prevention", "recruitment", "retention", "supportive-relationships", "strategy", "resource", "story"], default: ["story"], hint: "Add your topics here"}
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Related resources", required: false, name: "resources", widget: "relation", collection: "resources", value_field: "title", search_fields: ["title", "url"], multiple: true}
      - { label: "URL redirect(s)", minimize_collapsed: true, name: "redirectFrom", widget: "list", label_singular: "redirect", allow_add: true, field: {label: "URL", name: "url", widget: "string"}, required: false }
  - name: "resources"
    label: "Resources"
    folder: "resources"
    label_singular: "resource"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/resource.njk" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Name of resource", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false, hint: "Format your permalink like: '/resources/resource-name/'. Make sure to include the backslash at the end, and to omit the childwelfareplaybook.com domain." }
      - { label: "File type", name: "filetype", widget: "select", options: ["pdf", "doc", "link"] }
      - { label: "Link to resource", name: "url", widget: "string", required: false }
      - { label: "Upload resource", name: "file", widget: "file", media_library: { media_folder: "/assets/"}, required: false}
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["background-checks", "emergency-placements", "supporting-older-youth", "caregiver-licensing", "kin-engagement", "prevention", "recruitment", "retention", "supportive-relationships", "strategy", "resource", "story"], default: ["resource"], hint: "Add your topics here"}
      - { label: "Body", name: "description", widget: "markdown" }
      - { label: "URL redirect(s)", minimize_collapsed: true, name: "redirectFrom", widget: "list", label_singular: "redirect", allow_add: true, field: {label: "URL", name: "url", widget: "string"}, required: false }
  - name: "meetings"
    label: "Meetings"
    folder: "meetings"
    create: true
    label_singular: "meeting"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/meeting.njk" }
      - { label: "Template Engine", name: "templateEngineOverride", widget: "hidden", default: "md,njk" }
      - { label: "Date of meeting", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false, hint: "Format your permalink like: '/meetings/meeting-name/'. Make sure to include the backslash at the end, and to omit the childwelfareplaybook.com domain." }
      - { label: "YouTube ID", name: "youtubeId", widget: "string", hint: "The YouTube ID is the set of ~12 characters that appears after https://www.youtube.com/watch?v= in the video URL(s)." }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["background-checks", "emergency-placements", "supporting-older-youth", "caregiver-licensing", "kin-engagement", "prevention", "recruitment", "retention", "supportive-relationships", "strategy", "resource", "story"], default: ["story"], hint: "Add your topics here"}
      - { label: "Description of meeting", name: "body", widget: "markdown", required: false }
      - { label: "Related resources", required: false, name: "resources", widget: "relation", collection: "resources", value_field: "title", search_fields: ["title", "url"], multiple: true}
      - { label: "Related stories", required: false, name: "stories", widget: "relation", collection: "stories", value_field: "title", search_fields: ["title", "url"], multiple: true}
      - { label: "URL redirect(s)", minimize_collapsed: true, name: "redirectFrom", widget: "list", label_singular: "redirect", allow_add: true, field: {label: "URL", name: "url", widget: "string"}, required: false }